/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.project.hibernate.gui;

import com.project.hibernate.dao.MedecinDAO;
import com.project.hibernate.entity.Medecin;

/**
 *
 * @author Tsila
 */
public class JDialogFormMedecin extends javax.swing.JDialog {

    /**
     * Creates new form JDialogFormMedecin
     */
    private Medecin medecin = new Medecin();
    static String title = "";
    MedecinDAO medecinDAO = new MedecinDAO();
    
    //New
    public JDialogFormMedecin(java.awt.Frame parent, boolean modal,String title) {
        super(parent, modal);
        this.medecin = medecin;
        this.title = title;
        initComponents();
    }
    //Update
    public JDialogFormMedecin(java.awt.Frame parent, boolean modal,String title,Medecin medecin  ) {
        super(parent, modal);
        initComponents();
        this.medecin = medecin;
        this.title = title;
        System.out.println("ato ny modif : " +title);
        BtnAjoutFormMedecin.setText(title);
        txtFieldNameMedecin.setText(medecin.getNom());
        txtFieldFirstNameMedecin.setText(medecin.getPrenom());
        txtFieldGradeMedecin.setText(medecin.getGrade());
        
    }
    //Delete
    public JDialogFormMedecin(java.awt.Frame parent, boolean modal,Medecin medecin ,String title ) {
        super(parent, modal);
        initComponents();
        BtnAjoutFormMedecin.setText(title);
        this.medecin = medecin;
        this.title = title;
        System.out.println("ato ny suppression : " + title);
        txtFieldNameMedecin.setText(medecin.getNom());
        txtFieldFirstNameMedecin.setText(medecin.getPrenom());
        txtFieldGradeMedecin.setText(medecin.getGrade());
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFieldNameMedecin = new javax.swing.JTextField();
        txtFieldFirstNameMedecin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFieldGradeMedecin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BtnAjoutFormMedecin = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nom");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 21, -1, -1));

        txtFieldNameMedecin.setText("Nom");
        txtFieldNameMedecin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldNameMedecinActionPerformed(evt);
            }
        });
        getContentPane().add(txtFieldNameMedecin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 197, -1));

        txtFieldFirstNameMedecin.setText("Nom");
        txtFieldFirstNameMedecin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldFirstNameMedecinActionPerformed(evt);
            }
        });
        getContentPane().add(txtFieldFirstNameMedecin, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 111, 197, -1));

        jLabel2.setText("Prénom");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 77, -1, -1));

        txtFieldGradeMedecin.setText("Nom");
        txtFieldGradeMedecin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldGradeMedecinActionPerformed(evt);
            }
        });
        getContentPane().add(txtFieldGradeMedecin, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 186, 197, -1));

        jLabel3.setText("Grade");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 155, -1, -1));

        BtnAjoutFormMedecin.setText("Ajouter");
        BtnAjoutFormMedecin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAjoutFormMedecinActionPerformed(evt);
            }
        });
        getContentPane().add(BtnAjoutFormMedecin, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 237, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldNameMedecinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldNameMedecinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldNameMedecinActionPerformed

    private void txtFieldFirstNameMedecinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldFirstNameMedecinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldFirstNameMedecinActionPerformed

    private void txtFieldGradeMedecinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldGradeMedecinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldGradeMedecinActionPerformed

    private void BtnAjoutFormMedecinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAjoutFormMedecinActionPerformed
        if( this.title.equals("New")){
            this.medecin.setNom(txtFieldNameMedecin.getText());
            this.medecin.setPrenom(txtFieldFirstNameMedecin.getText());
            this.medecin.setGrade(txtFieldGradeMedecin.getText());
            medecinDAO.ajouterMedecin(this.medecin);
            this.dispose();
        }else if(this.title.equals("Update")){
            System.out.println("tonga ato aminy ilay modification :  " +this.title);
            this.medecin.setCodemed(medecin.getCodemed());
            this.medecin.setNom(txtFieldNameMedecin.getText());
            this.medecin.setPrenom(txtFieldFirstNameMedecin.getText());
            this.medecin.setGrade(txtFieldGradeMedecin.getText());
            medecinDAO.modifierMedecin(this.medecin);
            this.dispose();
        }else if (this.title.equals("Delete")){
            System.out.println("tonga ato aminy ilay suppretion de :  " +this.title);
            medecinDAO.supprimerMedecin(this.medecin.getCodemed());
            this.dispose();
        }
    }//GEN-LAST:event_BtnAjoutFormMedecinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogFormMedecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogFormMedecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogFormMedecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogFormMedecin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogFormMedecin dialog = new JDialogFormMedecin(new javax.swing.JFrame(), true,null,"");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtnAjoutFormMedecin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtFieldFirstNameMedecin;
    private javax.swing.JTextField txtFieldGradeMedecin;
    private javax.swing.JTextField txtFieldNameMedecin;
    // End of variables declaration//GEN-END:variables
}
