/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.project.hibernate.gui;

import com.project.hibernate.dao.PatientDAO;
import com.project.hibernate.entity.Patient;

/**
 *
 * @author Tsila
 */
public class JDialogFormPatient extends javax.swing.JDialog {

    /**
     * Creates new form JDialogFormPatient
     */
     private Patient patient = new Patient();
    static String title = "";
    PatientDAO patientDAO = new PatientDAO();
   
    
    //New
    public JDialogFormPatient(java.awt.Frame parent, boolean modal,String title) {
        super(parent, modal);
        this.patient = patient;
        this.title = title;
        initComponents();
    }
    
    //Update
    public JDialogFormPatient(java.awt.Frame parent, boolean modal,String title,Patient patient) {
        super(parent, modal);
        initComponents();
        this.patient = patient;
        this.title = title;
        System.out.println("ato ny modif : " +title);
        BtnAjoutFormPatient.setText(title);
        txtFieldNamePatient.setText(patient.getNom());
        txtFieldFirstNamePatient.setText(patient.getPrenom());
        txtFieldSexePatient.setText(patient.getSexe());
        txtFieldAdressePatient.setText(patient.getAdresse());
    }
    
    //Delete
    public JDialogFormPatient(java.awt.Frame parent, boolean modal,Patient patient,String title) {
        super(parent, modal);
        initComponents();
        this.patient = patient;
        this.title = title;
        System.out.println("ato ny modif : " +title);
        BtnAjoutFormPatient.setText(title);
        txtFieldNamePatient.setText(patient.getNom());
        txtFieldFirstNamePatient.setText(patient.getPrenom());
        txtFieldSexePatient.setText(patient.getSexe());
        txtFieldAdressePatient.setText(patient.getAdresse());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFieldNamePatient = new javax.swing.JTextField();
        BtnAjoutFormPatient = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        txtFieldFirstNamePatient = new javax.swing.JTextField();
        txtFieldAdressePatient = new javax.swing.JTextField();
        txtFieldSexePatient = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtFieldNamePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldNamePatientActionPerformed(evt);
            }
        });

        BtnAjoutFormPatient.setText("Ajouter");
        BtnAjoutFormPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAjoutFormPatientActionPerformed(evt);
            }
        });

        jLabel1.setText("Nom");

        txtFieldFirstNamePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldFirstNamePatientActionPerformed(evt);
            }
        });

        txtFieldAdressePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldAdressePatientActionPerformed(evt);
            }
        });

        txtFieldSexePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldSexePatientActionPerformed(evt);
            }
        });

        jLabel2.setText("Adresse");

        jLabel3.setText("Prénom");

        jLabel4.setText("Sexe");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(BtnAjoutFormPatient))
                    .addComponent(txtFieldFirstNamePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldAdressePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldSexePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtFieldNamePatient, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtFieldNamePatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtFieldFirstNamePatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(txtFieldAdressePatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFieldSexePatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(BtnAjoutFormPatient)
                .addGap(87, 87, 87))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldNamePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldNamePatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldNamePatientActionPerformed

    private void BtnAjoutFormPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAjoutFormPatientActionPerformed
        if( this.title.equals("New")){
            this.patient.setNom(txtFieldNamePatient.getText());
            this.patient.setPrenom(txtFieldFirstNamePatient.getText());
            this.patient.setSexe(txtFieldSexePatient.getText());
            this.patient.setAdresse(txtFieldAdressePatient.getText());
            patientDAO.ajouterPatient(this.patient);
            this.dispose();
        }else if(this.title.equals("Update")){
            System.out.println("tonga ato aminy ilay modification :  " +this.title);
            this.patient.setCodepat(patient.getCodepat());
            this.patient.setNom(txtFieldNamePatient.getText());
            this.patient.setPrenom(txtFieldFirstNamePatient.getText());
            this.patient.setSexe(txtFieldSexePatient.getText());
            this.patient.setAdresse(txtFieldAdressePatient.getText());
            patientDAO.modifierPatient(this.patient);
            this.dispose();
        }else if (this.title.equals("Delete")){
            System.out.println("tonga ato aminy ilay suppretion de :  " +this.title);
            patientDAO.supprimerPatient(this.patient.getCodepat());
            this.dispose();
        }
    }//GEN-LAST:event_BtnAjoutFormPatientActionPerformed

    private void txtFieldFirstNamePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldFirstNamePatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldFirstNamePatientActionPerformed

    private void txtFieldAdressePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldAdressePatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldAdressePatientActionPerformed

    private void txtFieldSexePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldSexePatientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldSexePatientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogFormPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogFormPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogFormPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogFormPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogFormPatient dialog = new JDialogFormPatient(new javax.swing.JFrame(),true,null,"");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtnAjoutFormPatient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtFieldAdressePatient;
    private javax.swing.JTextField txtFieldFirstNamePatient;
    private javax.swing.JTextField txtFieldNamePatient;
    private javax.swing.JTextField txtFieldSexePatient;
    // End of variables declaration//GEN-END:variables
}
