/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.project.hibernate.gui;

/**
 *
 * @author Tsila
 */
public class VisiterPanel extends javax.swing.JPanel {

    /**
     * Creates new form VisiterPanel
     */
    public VisiterPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableVisiter = new javax.swing.JTable();
        BtnAjoutVisiter = new javax.swing.JToggleButton();
        TxtFieldSearchVisiter = new javax.swing.JTextField();
        BtnSearchVisiter = new javax.swing.JButton();
        BtnModifierVisiter = new javax.swing.JToggleButton();
        BtnSupprimerVisiter = new javax.swing.JToggleButton();

        TableVisiter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableVisiter.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        TableVisiter.setMinimumSize(new java.awt.Dimension(2, 2));
        jScrollPane1.setViewportView(TableVisiter);

        BtnAjoutVisiter.setText("Ajouter");

        TxtFieldSearchVisiter.setText("Rechercher Visiter");
        TxtFieldSearchVisiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldSearchVisiterActionPerformed(evt);
            }
        });

        BtnSearchVisiter.setText("Rechercher");
        BtnSearchVisiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSearchVisiterActionPerformed(evt);
            }
        });

        BtnModifierVisiter.setText("Modifier");
        BtnModifierVisiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModifierVisiterActionPerformed(evt);
            }
        });

        BtnSupprimerVisiter.setText("Supprimer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnAjoutVisiter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TxtFieldSearchVisiter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnSearchVisiter))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnModifierVisiter)
                        .addGap(26, 26, 26)
                        .addComponent(BtnSupprimerVisiter))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAjoutVisiter)
                    .addComponent(TxtFieldSearchVisiter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSearchVisiter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnModifierVisiter)
                    .addComponent(BtnSupprimerVisiter))
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnModifierVisiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModifierVisiterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnModifierVisiterActionPerformed

    private void BtnSearchVisiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchVisiterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSearchVisiterActionPerformed

    private void TxtFieldSearchVisiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldSearchVisiterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldSearchVisiterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtnAjoutVisiter;
    private javax.swing.JToggleButton BtnModifierVisiter;
    private javax.swing.JButton BtnSearchVisiter;
    private javax.swing.JToggleButton BtnSupprimerVisiter;
    private javax.swing.JTable TableVisiter;
    private javax.swing.JTextField TxtFieldSearchVisiter;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
